import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ViewCanvas from "./components/ViewCanvas";

const Alpino = localFont({
  src: "../public/fonts/Alpino-Variable.woff2",
});

export const metadata: Metadata = {
  title: "Vcola",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${Alpino.className} h-full antialiased`}>
      <body className="overflow-x-hidden bg-yellow-300">
        {children}
        <ViewCanvas />
      </body>
    </html>
  );
}
